# Configuration for MyST-based GitHub Pages site
layout: default
title: Cal-ICOR
author: Sean Morris
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sass-converter
markdown: kramdown
sass:
  style: compressed
  source_map: true
